In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("weather.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [11]:
df.replace([-99999,-88888],np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [9]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [13]:
df.replace({
    'temperature' : -99999,
    'windspeed' : [-99999,-88888],
    'event' : 'no event'
},np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN

In [14]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [15]:
df.replace({
    -99999 : np.nan,
    -88888 : np.nan,
    'no event' : np.nan
})

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN