In [15]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek

## Load Data:

In [3]:
df = pd.read_csv('churn.csv')
df.shape

(3150, 14)

In [4]:
df.head()

   Call  Failure  Complains  Subscription  Length  Charge  Amount  ...  Status  Age  Customer Value  Churn
0              8          0                    38               0  ...       1   30         197.640      0
1              0          0                    39               0  ...       2   25          46.035      0
2             10          0                    37               0  ...       1   30        1536.520      0
3             10          0                    38               0  ...       1   15         240.020      0
4              3          0                    38               0  ...       1   15         145.805      0

[5 rows x 14 columns]

In [9]:
df['Churn'].value_counts()

Churn
0    2655
1     495
Name: count, dtype: int64

In [11]:
# Check if any null values
df.isnull().sum()

Call  Failure              0
Complains                  0
Subscription  Length       0
Charge  Amount             0
Seconds of Use             0
Frequency of use           0
Frequency of SMS           0
Distinct Called Numbers    0
Age Group                  0
Tariff Plan                0
Status                     0
Age                        0
Customer Value             0
Churn                      0
dtype: int64

In [14]:
# Decide feartures and target variable
X = df.drop('Churn', axis = 1)
y = df['Churn']

X.head()

   Call  Failure  Complains  Subscription  Length  Charge  Amount  ...  Tariff Plan  Status  Age  Customer Value
0              8          0                    38               0  ...            1       1   30         197.640
1              0          0                    39               0  ...            1       2   25          46.035
2             10          0                    37               0  ...            1       1   30        1536.520
3             10          0                    38               0  ...            1       1   15         240.020
4              3          0                    38               0  ...            1       1   15         145.805

[5 rows x 13 columns]

## Model Training:

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2, stratify=y)

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.98      0.94       531
           1       0.84      0.41      0.55        99

    accuracy                           0.90       630
   macro avg       0.87      0.70      0.75       630
weighted avg       0.89      0.90      0.88       630

C:\Users\ANSHH\anaconda3\envs\dsenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

As we can see that the recall percent is too low that means if customer is going to churn we are able to catch only 41% of them. Which is really horrible. That's happening becuase of class imbalance.

We have to fix the recall percentage coz that's most important for our model.

## Under Sampling:

In [23]:
rus = RandomUnderSampler()
X_train_rus, y_train_rus = rus.fit_resample(X_train, y_train)
y_train_rus.value_counts()

Churn
0    396
1    396
Name: count, dtype: int64

Here we can see that we did undersampling so number of records of majority class became same as minority class

In [25]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train_rus, y_train_rus)

y_pred_rus = model.predict(X_test)

report = classification_report(y_test, y_pred_rus)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.83      0.89       531
           1       0.49      0.87      0.62        99

    accuracy                           0.83       630
   macro avg       0.73      0.85      0.76       630
weighted avg       0.90      0.83      0.85       630

C:\Users\ANSHH\anaconda3\envs\dsenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

So here we can see that our recall is improved a lot with the help of undersampling

## Over Sampling : SMOTE

In [26]:
smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
y_train_smote.value_counts()

Churn
0    2124
1    2124
Name: count, dtype: int64

In [27]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train_smote, y_train_smote)

y_pred_smote = model.predict(X_test)

report = classification_report(y_test, y_pred_smote)
print(report)

              precision    recall  f1-score   support

           0       0.96      0.81      0.88       531
           1       0.45      0.84      0.58        99

    accuracy                           0.81       630
   macro avg       0.71      0.82      0.73       630
weighted avg       0.88      0.81      0.83       630

C:\Users\ANSHH\anaconda3\envs\dsenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Over Sampling : SMOTE Tomek

In [31]:
tomek = SMOTETomek()
X_train_tomek, y_train_tomek = tomek.fit_resample(X_train, y_train)

y_train_tomek.value_counts()

Churn
0    2093
1    2093
Name: count, dtype: int64

Why the values are lesser than SMOTE?
- Because it removed some of the synthetic data points which our coming in majority class's boundry.

In [32]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train_tomek, y_train_tomek)

y_pred_tomek = model.predict(X_test)

report = classification_report(y_test, y_pred_tomek)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.81      0.88       531
           1       0.45      0.85      0.59        99

    accuracy                           0.81       630
   macro avg       0.71      0.83      0.73       630
weighted avg       0.88      0.81      0.83       630

C:\Users\ANSHH\anaconda3\envs\dsenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(