In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [4]:
df = pd.read_csv("stock_data.csv",header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [6]:
df = pd.read_csv("stock_data.csv",skiprows=1, names = ["stock-name","eps","revenue","price","people"])
df

  stock-name            eps  revenue  price         people
0    tickers            eps  revenue  price         people
1      GOOGL          27.82       87    845     larry page
2        WMT           4.61      484     65           n.a.
3       MSFT             -1       85     64     bill gates
4       RIL   not available       50   1023  mukesh ambani
5       TATA            5.6       -1   n.a.     ratan tata

In [7]:
df = pd.read_csv("stock_data.csv",skiprows=1, nrows = 2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [10]:
df = pd.read_csv("stock_data.csv",skiprows=1, na_values={"not available",-1,"n.a."})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [18]:
df_movies = pd.read_excel("movies_db.xlsx","movies")
df_movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [19]:
df_financials = pd.read_excel("movies_db.xlsx","financials")
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [22]:
df_financials.currency.value_counts()

currency
USD        20
INR        18
$$          1
Dollars     1
Name: count, dtype: int64

In [23]:
def standerdize_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    else:
        return curr
df_financials = pd.read_excel("movies_db.xlsx","financials", converters={'currency': standerdize_currency})
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [27]:
df_merged = pd.merge(df_movies,df_financials, on = "movie_id")
df_merged.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

In [29]:
df_merged.to_excel("movies_merged.xlsx", index = False)