In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("weather_data.csv")
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [10]:
type(df.day[0]) # But the day column value type is str

str

In [17]:
# Let's convert it into date data type 

df = pd.read_csv("weather_data.csv", parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [13]:
# Now let's handle null vales

df.fillna(0)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        9.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08          0.0        0.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [18]:
df.set_index("day",inplace = True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [22]:
df.fillna({
    "temperature" : df.temperature.mean(),
    "windspeed" : df.windspeed.mean(),
    "event" : "No Event"
})

            temperature  windspeed     event
day
2017-01-01        32.00       6.00      Rain
2017-01-04        33.22       9.00     Sunny
2017-01-05        28.00       8.42      Snow
2017-01-06        33.22       7.00  No Event
2017-01-07        32.00       8.42      Rain
2017-01-08        33.22       8.42     Sunny
2017-01-09        33.22       8.42  No Event
2017-01-10        34.10       8.10    Cloudy
2017-01-11        40.00      12.00     Sunny

In [28]:
df.ffill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [27]:
df.bfill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [29]:
df.interpolate()

C:\Users\ANSHH\AppData\Local\Temp\ipykernel_27908\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [35]:
df.dropna()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [36]:
df.dropna(how ="all")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [38]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [39]:
df.dropna(thresh = 2)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny